const path = require("path");
const webpack = require("webpack");
const fs = require("fs-extra"); // You'll need fs-extra to copy files
const packageJson = require("./package.json");
const TerserPlugin = require("terser-webpack-plugin");

module.exports = {
  entry: "./src/js/index.js",
  output: {
    // Main entry file will have the version number
    filename: "[name]_" + packageJson.version + ".js",
    // Other chunk files will be handled by chunkFilename
    chunkFilename: "[name].[chunkhash].js", // Keep chunk hash for cache busting
    path: path.resolve(__dirname, "dist", packageJson.version), // Version-specific output directory
    globalObject: "this",
  },
  plugins: [
    new webpack.DefinePlugin({
      APP_CONFIG: JSON.stringify({
        version: packageJson.version,
        githubPagesBase: "https://penwern.github.io/curate-dev-js",
        replayBase: `https://penwern.github.io/curate-dev-js/${packageJson.version}/replay/`,
      }),
    }),
    // Custom plugin to handle the creation of the @latest folder AND ReplayWeb service worker
    {
      apply(compiler) {
        compiler.hooks.afterEmit.tapAsync(
          "CopyLatestBuildAndReplayWorker",
          (compilation, callback) => {
            const versionDir = path.resolve(
              __dirname,
              "dist",
              packageJson.version
            );
            const latestDir = path.resolve(__dirname, "dist", "@latest");

            // Make sure the @latest folder exists
            fs.emptyDirSync(latestDir); // Remove old contents if any

            // Create ReplayWeb service worker content
            const replayWorkerContent = `// ReplayWeb.page service worker
// Auto-generated by webpack build
importScripts("https://cdn.jsdelivr.net/npm/replaywebpage@2.3.12/sw.js");`;

            // Create replay directory and service worker in both version and @latest
            const createReplayWorker = (targetDir) => {
              const replayDir = path.resolve(targetDir, "replay");
              fs.ensureDirSync(replayDir);
              fs.writeFileSync(
                path.resolve(replayDir, "sw.js"),
                replayWorkerContent
              );
              console.log(
                `Created ReplayWeb service worker in ${targetDir}/replay/sw.js`
              );
            };

            // Create in version directory
            createReplayWorker(versionDir);
            // Create in @latest directory
            createReplayWorker(latestDir);

            // Copy versioned files to @latest folder without version numbers
            fs.readdir(versionDir, (err, files) => {
              if (err) {
                console.error("Error reading versioned files:", err);
                return callback();
              }

              files.forEach((file) => {
                // Skip the replay directory since we already handled it
                if (file === "replay") return;

                const sourcePath = path.resolve(versionDir, file);
                const targetPath = path.resolve(
                  latestDir,
                  file.replace(`_${packageJson.version}.js`, ".js")
                );

                // Copy each file to the @latest folder with the correct filename
                fs.copy(sourcePath, targetPath, (copyErr) => {
                  if (copyErr) {
                    console.error(
                      `Error copying file to @latest: ${file}`,
                      copyErr
                    );
                  } else {
                    console.log(`Successfully copied ${file} to @latest`);
                  }
                });
              });
              callback(); // Don't forget to call callback to signal Webpack we're done
            });
          }
        );
      },
    },
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(@material\/web|lit)\/).*/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-env"],
          },
        },
      },
      {
        test: /\.worker\.js$/,
        include: [path.resolve(__dirname, "src/js/workers")],
        use: {
          loader: "worker-loader",
          options: {
            filename: "[name].[hash].worker.js",
          },
        },
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()],
    // The splitChunks block is now gone
  },
};
