name: Webpack Build

# Trigger the workflow on push to main (or your default branch)
on:
  push:
    branches:
      - main # You can change this to your default branch (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest # Using the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Check out the repository so we can work with it

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Set the Node.js version (adjust as needed)

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache the npm modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }} # Cache key based on package-lock
          restore-keys: |
            ${{ runner.os }}-node-modules-  # Fallback cache key if no exact match found

      - name: Install dependencies
        run: |
          npm install  # Install dependencies (this will be faster if cache hits)

      - name: Build with Webpack
        run: |
          npm run build  # Run your Webpack build (assuming it's defined in your package.json)

      - name: Upload Build Artifacts (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: webpack-build
          path: ./dist # Path to your build output (e.g., the dist folder)
